name: DAST
on:
  push:

jobs:
  test-dast:
    name: test-dast
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install build-essential and python
        run: sudo apt-get install -y build-essential python
      - name: Get NPM Cache Dir
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Enable NPM Cache on package-lock file
        uses: actions/cache@v1
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install NPM dependencies and build Userbase
        run: |
          npm run ci:install
          npm run build:userbase-js:script
      - name: Run Browser Tests
        run: npm run ci:start # this will start server in localhost:8080
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Dastardly Action Step
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'http://localhost:3000'
      - name: Publish Test Report
        if: always()                                    # Forces this step to always run
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/dastardly-report.xml'       # You need to update this path if you pass in a different output filename to the Dastardly action
          require_tests: true
